GO_VERSION := $(shell awk '$$1 == "go" {print $$2; exit}' go.mod)
PROTOC_GEN_GO_VERSION := $(shell awk '$$1 == "google.golang.org/protobuf" {print $$2; exit}' go.mod)
GO_ALPINE_VERSION := 3.23
ALPINE_VERSION := 3.23.3
PROTOC_VERSION := 34.0
PROTOC_GEN_GO_GRPC_VERSION := 1.5.1
GOIMPORTS_VERSION := 0.31.0
PYTHON_VERSION := 3.13
GITLEAKS_VERSION := 8.24.2
VERSION_VARS := GO_VERSION PROTOC_GEN_GO_VERSION GO_ALPINE_VERSION ALPINE_VERSION PROTOC_VERSION PROTOC_GEN_GO_GRPC_VERSION GOIMPORTS_VERSION PYTHON_VERSION GITLEAKS_VERSION
export $(VERSION_VARS)
