import pathlib
import subprocess

path = pathlib.Path(
    subprocess.check_output(
        ["git", "rev-parse", "--git-path", "hooks/pre-commit"], text=True
    ).strip()
)
configured = subprocess.run(
    ["git", "config", "--get", "core.hooksPath"], capture_output=True, text=True
)
if configured.returncode == 0:
    raise SystemExit("core.hooksPath is configured; review existing hook system first")
if path.is_symlink() or (path.exists() and "File generated by pre-commit" not in path.read_text()):
    raise SystemExit("refusing to overwrite an unknown hook")
subprocess.run([".tools/bin/pre-commit", "install"], check=True)
