// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.34.0
// source: api/registration.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Update struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Actor         int64                  `protobuf:"varint,2,opt,name=actor,proto3" json:"actor,omitempty"`
	Chat          int64                  `protobuf:"varint,3,opt,name=chat,proto3" json:"chat,omitempty"`
	ChatType      string                 `protobuf:"bytes,4,opt,name=chat_type,json=chatType,proto3" json:"chat_type,omitempty"`
	Username      string                 `protobuf:"bytes,5,opt,name=username,proto3" json:"username,omitempty"`
	DisplayName   string                 `protobuf:"bytes,6,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Text          string                 `protobuf:"bytes,7,opt,name=text,proto3" json:"text,omitempty"`
	Callback      string                 `protobuf:"bytes,8,opt,name=callback,proto3" json:"callback,omitempty"`
	Phone         string                 `protobuf:"bytes,9,opt,name=phone,proto3" json:"phone,omitempty"`
	ContactOwner  int64                  `protobuf:"varint,10,opt,name=contact_owner,json=contactOwner,proto3" json:"contact_owner,omitempty"`
	MessageId     int64                  `protobuf:"varint,11,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Kind          string                 `protobuf:"bytes,12,opt,name=kind,proto3" json:"kind,omitempty"`
	MemberId      int64                  `protobuf:"varint,13,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	MemberActive  bool                   `protobuf:"varint,14,opt,name=member_active,json=memberActive,proto3" json:"member_active,omitempty"`
	ChatTitle     string                 `protobuf:"bytes,15,opt,name=chat_title,json=chatTitle,proto3" json:"chat_title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Update) Reset() {
	*x = Update{}
	mi := &file_api_registration_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Update) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Update) ProtoMessage() {}

func (x *Update) ProtoReflect() protoreflect.Message {
	mi := &file_api_registration_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Update.ProtoReflect.Descriptor instead.
func (*Update) Descriptor() ([]byte, []int) {
	return file_api_registration_proto_rawDescGZIP(), []int{0}
}

func (x *Update) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Update) GetActor() int64 {
	if x != nil {
		return x.Actor
	}
	return 0
}

func (x *Update) GetChat() int64 {
	if x != nil {
		return x.Chat
	}
	return 0
}

func (x *Update) GetChatType() string {
	if x != nil {
		return x.ChatType
	}
	return ""
}

func (x *Update) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Update) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Update) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Update) GetCallback() string {
	if x != nil {
		return x.Callback
	}
	return ""
}

func (x *Update) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *Update) GetContactOwner() int64 {
	if x != nil {
		return x.ContactOwner
	}
	return 0
}

func (x *Update) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *Update) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Update) GetMemberId() int64 {
	if x != nil {
		return x.MemberId
	}
	return 0
}

func (x *Update) GetMemberActive() bool {
	if x != nil {
		return x.MemberActive
	}
	return false
}

func (x *Update) GetChatTitle() string {
	if x != nil {
		return x.ChatTitle
	}
	return ""
}

type Receipt struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Duplicate     bool                   `protobuf:"varint,1,opt,name=duplicate,proto3" json:"duplicate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Receipt) Reset() {
	*x = Receipt{}
	mi := &file_api_registration_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Receipt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Receipt) ProtoMessage() {}

func (x *Receipt) ProtoReflect() protoreflect.Message {
	mi := &file_api_registration_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Receipt.ProtoReflect.Descriptor instead.
func (*Receipt) Descriptor() ([]byte, []int) {
	return file_api_registration_proto_rawDescGZIP(), []int{1}
}

func (x *Receipt) GetDuplicate() bool {
	if x != nil {
		return x.Duplicate
	}
	return false
}

type Field struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Field) Reset() {
	*x = Field{}
	mi := &file_api_registration_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Field) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Field) ProtoMessage() {}

func (x *Field) ProtoReflect() protoreflect.Message {
	mi := &file_api_registration_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Field.ProtoReflect.Descriptor instead.
func (*Field) Descriptor() ([]byte, []int) {
	return file_api_registration_proto_rawDescGZIP(), []int{2}
}

func (x *Field) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Field) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type Button struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LabelKey      string                 `protobuf:"bytes,1,opt,name=label_key,json=labelKey,proto3" json:"label_key,omitempty"`
	Data          string                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Button) Reset() {
	*x = Button{}
	mi := &file_api_registration_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Button) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Button) ProtoMessage() {}

func (x *Button) ProtoReflect() protoreflect.Message {
	mi := &file_api_registration_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Button.ProtoReflect.Descriptor instead.
func (*Button) Descriptor() ([]byte, []int) {
	return file_api_registration_proto_rawDescGZIP(), []int{3}
}

func (x *Button) GetLabelKey() string {
	if x != nil {
		return x.LabelKey
	}
	return ""
}

func (x *Button) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type View struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Field         string                 `protobuf:"bytes,2,opt,name=field,proto3" json:"field,omitempty"`
	Fields        []*Field               `protobuf:"bytes,3,rep,name=fields,proto3" json:"fields,omitempty"`
	Buttons       []*Button              `protobuf:"bytes,4,rep,name=buttons,proto3" json:"buttons,omitempty"`
	Numbers       []int64                `protobuf:"varint,5,rep,packed,name=numbers,proto3" json:"numbers,omitempty"`
	Code          string                 `protobuf:"bytes,6,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *View) Reset() {
	*x = View{}
	mi := &file_api_registration_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *View) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*View) ProtoMessage() {}

func (x *View) ProtoReflect() protoreflect.Message {
	mi := &file_api_registration_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use View.ProtoReflect.Descriptor instead.
func (*View) Descriptor() ([]byte, []int) {
	return file_api_registration_proto_rawDescGZIP(), []int{4}
}

func (x *View) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *View) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *View) GetFields() []*Field {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *View) GetButtons() []*Button {
	if x != nil {
		return x.Buttons
	}
	return nil
}

func (x *View) GetNumbers() []int64 {
	if x != nil {
		return x.Numbers
	}
	return nil
}

func (x *View) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type ClaimRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Worker        string                 `protobuf:"bytes,2,opt,name=worker,proto3" json:"worker,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimRequest) Reset() {
	*x = ClaimRequest{}
	mi := &file_api_registration_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimRequest) ProtoMessage() {}

func (x *ClaimRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_registration_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimRequest.ProtoReflect.Descriptor instead.
func (*ClaimRequest) Descriptor() ([]byte, []int) {
	return file_api_registration_proto_rawDescGZIP(), []int{5}
}

func (x *ClaimRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ClaimRequest) GetWorker() string {
	if x != nil {
		return x.Worker
	}
	return ""
}

type Delivery struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Lease           string                 `protobuf:"bytes,2,opt,name=lease,proto3" json:"lease,omitempty"`
	Chat            int64                  `protobuf:"varint,3,opt,name=chat,proto3" json:"chat,omitempty"`
	Kind            string                 `protobuf:"bytes,4,opt,name=kind,proto3" json:"kind,omitempty"`
	View            *View                  `protobuf:"bytes,5,opt,name=view,proto3" json:"view,omitempty"`
	SourceChat      int64                  `protobuf:"varint,6,opt,name=source_chat,json=sourceChat,proto3" json:"source_chat,omitempty"`
	SourceMessage   int64                  `protobuf:"varint,7,opt,name=source_message,json=sourceMessage,proto3" json:"source_message,omitempty"`
	Actor           int64                  `protobuf:"varint,8,opt,name=actor,proto3" json:"actor,omitempty"`
	Traceparent     string                 `protobuf:"bytes,9,opt,name=traceparent,proto3" json:"traceparent,omitempty"`
	NotBeforeUnixMs int64                  `protobuf:"varint,10,opt,name=not_before_unix_ms,json=notBeforeUnixMs,proto3" json:"not_before_unix_ms,omitempty"`
	Group           bool                   `protobuf:"varint,11,opt,name=group,proto3" json:"group,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Delivery) Reset() {
	*x = Delivery{}
	mi := &file_api_registration_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Delivery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Delivery) ProtoMessage() {}

func (x *Delivery) ProtoReflect() protoreflect.Message {
	mi := &file_api_registration_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Delivery.ProtoReflect.Descriptor instead.
func (*Delivery) Descriptor() ([]byte, []int) {
	return file_api_registration_proto_rawDescGZIP(), []int{6}
}

func (x *Delivery) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Delivery) GetLease() string {
	if x != nil {
		return x.Lease
	}
	return ""
}

func (x *Delivery) GetChat() int64 {
	if x != nil {
		return x.Chat
	}
	return 0
}

func (x *Delivery) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Delivery) GetView() *View {
	if x != nil {
		return x.View
	}
	return nil
}

func (x *Delivery) GetSourceChat() int64 {
	if x != nil {
		return x.SourceChat
	}
	return 0
}

func (x *Delivery) GetSourceMessage() int64 {
	if x != nil {
		return x.SourceMessage
	}
	return 0
}

func (x *Delivery) GetActor() int64 {
	if x != nil {
		return x.Actor
	}
	return 0
}

func (x *Delivery) GetTraceparent() string {
	if x != nil {
		return x.Traceparent
	}
	return ""
}

func (x *Delivery) GetNotBeforeUnixMs() int64 {
	if x != nil {
		return x.NotBeforeUnixMs
	}
	return 0
}

func (x *Delivery) GetGroup() bool {
	if x != nil {
		return x.Group
	}
	return false
}

type Completion struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Lease             string                 `protobuf:"bytes,2,opt,name=lease,proto3" json:"lease,omitempty"`
	Outcome           string                 `protobuf:"bytes,3,opt,name=outcome,proto3" json:"outcome,omitempty"`
	TelegramMessageId int64                  `protobuf:"varint,4,opt,name=telegram_message_id,json=telegramMessageId,proto3" json:"telegram_message_id,omitempty"`
	RetryAfterSeconds int64                  `protobuf:"varint,5,opt,name=retry_after_seconds,json=retryAfterSeconds,proto3" json:"retry_after_seconds,omitempty"`
	ErrorCode         string                 `protobuf:"bytes,6,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	NextAfter         int64                  `protobuf:"varint,7,opt,name=next_after,json=nextAfter,proto3" json:"next_after,omitempty"`
	Checked           int64                  `protobuf:"varint,8,opt,name=checked,proto3" json:"checked,omitempty"`
	FailedMembers     int64                  `protobuf:"varint,9,opt,name=failed_members,json=failedMembers,proto3" json:"failed_members,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Completion) Reset() {
	*x = Completion{}
	mi := &file_api_registration_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Completion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Completion) ProtoMessage() {}

func (x *Completion) ProtoReflect() protoreflect.Message {
	mi := &file_api_registration_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Completion.ProtoReflect.Descriptor instead.
func (*Completion) Descriptor() ([]byte, []int) {
	return file_api_registration_proto_rawDescGZIP(), []int{7}
}

func (x *Completion) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Completion) GetLease() string {
	if x != nil {
		return x.Lease
	}
	return ""
}

func (x *Completion) GetOutcome() string {
	if x != nil {
		return x.Outcome
	}
	return ""
}

func (x *Completion) GetTelegramMessageId() int64 {
	if x != nil {
		return x.TelegramMessageId
	}
	return 0
}

func (x *Completion) GetRetryAfterSeconds() int64 {
	if x != nil {
		return x.RetryAfterSeconds
	}
	return 0
}

func (x *Completion) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *Completion) GetNextAfter() int64 {
	if x != nil {
		return x.NextAfter
	}
	return 0
}

func (x *Completion) GetChecked() int64 {
	if x != nil {
		return x.Checked
	}
	return 0
}

func (x *Completion) GetFailedMembers() int64 {
	if x != nil {
		return x.FailedMembers
	}
	return 0
}

type ExportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Actor         int64                  `protobuf:"varint,1,opt,name=actor,proto3" json:"actor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportRequest) Reset() {
	*x = ExportRequest{}
	mi := &file_api_registration_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportRequest) ProtoMessage() {}

func (x *ExportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_registration_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportRequest.ProtoReflect.Descriptor instead.
func (*ExportRequest) Descriptor() ([]byte, []int) {
	return file_api_registration_proto_rawDescGZIP(), []int{8}
}

func (x *ExportRequest) GetActor() int64 {
	if x != nil {
		return x.Actor
	}
	return 0
}

type ExportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Xlsx          []byte                 `protobuf:"bytes,1,opt,name=xlsx,proto3" json:"xlsx,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportResponse) Reset() {
	*x = ExportResponse{}
	mi := &file_api_registration_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportResponse) ProtoMessage() {}

func (x *ExportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_registration_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportResponse.ProtoReflect.Descriptor instead.
func (*ExportResponse) Descriptor() ([]byte, []int) {
	return file_api_registration_proto_rawDescGZIP(), []int{9}
}

func (x *ExportResponse) GetXlsx() []byte {
	if x != nil {
		return x.Xlsx
	}
	return nil
}

type MembersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Actor         int64                  `protobuf:"varint,1,opt,name=actor,proto3" json:"actor,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	After         int64                  `protobuf:"varint,3,opt,name=after,proto3" json:"after,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MembersRequest) Reset() {
	*x = MembersRequest{}
	mi := &file_api_registration_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MembersRequest) ProtoMessage() {}

func (x *MembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_registration_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MembersRequest.ProtoReflect.Descriptor instead.
func (*MembersRequest) Descriptor() ([]byte, []int) {
	return file_api_registration_proto_rawDescGZIP(), []int{10}
}

func (x *MembersRequest) GetActor() int64 {
	if x != nil {
		return x.Actor
	}
	return 0
}

func (x *MembersRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *MembersRequest) GetAfter() int64 {
	if x != nil {
		return x.After
	}
	return 0
}

type MembersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chat          int64                  `protobuf:"varint,1,opt,name=chat,proto3" json:"chat,omitempty"`
	Users         []int64                `protobuf:"varint,2,rep,packed,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MembersResponse) Reset() {
	*x = MembersResponse{}
	mi := &file_api_registration_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MembersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MembersResponse) ProtoMessage() {}

func (x *MembersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_registration_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MembersResponse.ProtoReflect.Descriptor instead.
func (*MembersResponse) Descriptor() ([]byte, []int) {
	return file_api_registration_proto_rawDescGZIP(), []int{11}
}

func (x *MembersResponse) GetChat() int64 {
	if x != nil {
		return x.Chat
	}
	return 0
}

func (x *MembersResponse) GetUsers() []int64 {
	if x != nil {
		return x.Users
	}
	return nil
}

type SyncMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Actor         int64                  `protobuf:"varint,1,opt,name=actor,proto3" json:"actor,omitempty"`
	Chat          int64                  `protobuf:"varint,2,opt,name=chat,proto3" json:"chat,omitempty"`
	User          int64                  `protobuf:"varint,3,opt,name=user,proto3" json:"user,omitempty"`
	Active        bool                   `protobuf:"varint,4,opt,name=active,proto3" json:"active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncMemberRequest) Reset() {
	*x = SyncMemberRequest{}
	mi := &file_api_registration_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncMemberRequest) ProtoMessage() {}

func (x *SyncMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_registration_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncMemberRequest.ProtoReflect.Descriptor instead.
func (*SyncMemberRequest) Descriptor() ([]byte, []int) {
	return file_api_registration_proto_rawDescGZIP(), []int{12}
}

func (x *SyncMemberRequest) GetActor() int64 {
	if x != nil {
		return x.Actor
	}
	return 0
}

func (x *SyncMemberRequest) GetChat() int64 {
	if x != nil {
		return x.Chat
	}
	return 0
}

func (x *SyncMemberRequest) GetUser() int64 {
	if x != nil {
		return x.User
	}
	return 0
}

func (x *SyncMemberRequest) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

var File_api_registration_proto protoreflect.FileDescriptor

const file_api_registration_proto_rawDesc = "" +
	"\n" +
	"\x16api/registration.proto\x12\x0fregistration.v1\"\x9d\x03\n" +
	"\x06Update\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05actor\x18\x02 \x01(\x03R\x05actor\x12\x12\n" +
	"\x04chat\x18\x03 \x01(\x03R\x04chat\x12\x1b\n" +
	"\tchat_type\x18\x04 \x01(\tR\bchatType\x12\x1a\n" +
	"\busername\x18\x05 \x01(\tR\busername\x12!\n" +
	"\fdisplay_name\x18\x06 \x01(\tR\vdisplayName\x12\x12\n" +
	"\x04text\x18\a \x01(\tR\x04text\x12\x1a\n" +
	"\bcallback\x18\b \x01(\tR\bcallback\x12\x14\n" +
	"\x05phone\x18\t \x01(\tR\x05phone\x12#\n" +
	"\rcontact_owner\x18\n" +
	" \x01(\x03R\fcontactOwner\x12\x1d\n" +
	"\n" +
	"message_id\x18\v \x01(\x03R\tmessageId\x12\x12\n" +
	"\x04kind\x18\f \x01(\tR\x04kind\x12\x1b\n" +
	"\tmember_id\x18\r \x01(\x03R\bmemberId\x12#\n" +
	"\rmember_active\x18\x0e \x01(\bR\fmemberActive\x12\x1d\n" +
	"\n" +
	"chat_title\x18\x0f \x01(\tR\tchatTitle\"'\n" +
	"\aReceipt\x12\x1c\n" +
	"\tduplicate\x18\x01 \x01(\bR\tduplicate\"/\n" +
	"\x05Field\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"9\n" +
	"\x06Button\x12\x1b\n" +
	"\tlabel_key\x18\x01 \x01(\tR\blabelKey\x12\x12\n" +
	"\x04data\x18\x02 \x01(\tR\x04data\"\xc1\x01\n" +
	"\x04View\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x14\n" +
	"\x05field\x18\x02 \x01(\tR\x05field\x12.\n" +
	"\x06fields\x18\x03 \x03(\v2\x16.registration.v1.FieldR\x06fields\x121\n" +
	"\abuttons\x18\x04 \x03(\v2\x17.registration.v1.ButtonR\abuttons\x12\x18\n" +
	"\anumbers\x18\x05 \x03(\x03R\anumbers\x12\x12\n" +
	"\x04code\x18\x06 \x01(\tR\x04code\"6\n" +
	"\fClaimRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06worker\x18\x02 \x01(\tR\x06worker\"\xc6\x02\n" +
	"\bDelivery\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05lease\x18\x02 \x01(\tR\x05lease\x12\x12\n" +
	"\x04chat\x18\x03 \x01(\x03R\x04chat\x12\x12\n" +
	"\x04kind\x18\x04 \x01(\tR\x04kind\x12)\n" +
	"\x04view\x18\x05 \x01(\v2\x15.registration.v1.ViewR\x04view\x12\x1f\n" +
	"\vsource_chat\x18\x06 \x01(\x03R\n" +
	"sourceChat\x12%\n" +
	"\x0esource_message\x18\a \x01(\x03R\rsourceMessage\x12\x14\n" +
	"\x05actor\x18\b \x01(\x03R\x05actor\x12 \n" +
	"\vtraceparent\x18\t \x01(\tR\vtraceparent\x12+\n" +
	"\x12not_before_unix_ms\x18\n" +
	" \x01(\x03R\x0fnotBeforeUnixMs\x12\x14\n" +
	"\x05group\x18\v \x01(\bR\x05group\"\xab\x02\n" +
	"\n" +
	"Completion\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05lease\x18\x02 \x01(\tR\x05lease\x12\x18\n" +
	"\aoutcome\x18\x03 \x01(\tR\aoutcome\x12.\n" +
	"\x13telegram_message_id\x18\x04 \x01(\x03R\x11telegramMessageId\x12.\n" +
	"\x13retry_after_seconds\x18\x05 \x01(\x03R\x11retryAfterSeconds\x12\x1d\n" +
	"\n" +
	"error_code\x18\x06 \x01(\tR\terrorCode\x12\x1d\n" +
	"\n" +
	"next_after\x18\a \x01(\x03R\tnextAfter\x12\x18\n" +
	"\achecked\x18\b \x01(\x03R\achecked\x12%\n" +
	"\x0efailed_members\x18\t \x01(\x03R\rfailedMembers\"%\n" +
	"\rExportRequest\x12\x14\n" +
	"\x05actor\x18\x01 \x01(\x03R\x05actor\"$\n" +
	"\x0eExportResponse\x12\x12\n" +
	"\x04xlsx\x18\x01 \x01(\fR\x04xlsx\"P\n" +
	"\x0eMembersRequest\x12\x14\n" +
	"\x05actor\x18\x01 \x01(\x03R\x05actor\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x12\x14\n" +
	"\x05after\x18\x03 \x01(\x03R\x05after\";\n" +
	"\x0fMembersResponse\x12\x12\n" +
	"\x04chat\x18\x01 \x01(\x03R\x04chat\x12\x14\n" +
	"\x05users\x18\x02 \x03(\x03R\x05users\"i\n" +
	"\x11SyncMemberRequest\x12\x14\n" +
	"\x05actor\x18\x01 \x01(\x03R\x05actor\x12\x12\n" +
	"\x04chat\x18\x02 \x01(\x03R\x04chat\x12\x12\n" +
	"\x04user\x18\x03 \x01(\x03R\x04user\x12\x16\n" +
	"\x06active\x18\x04 \x01(\bR\x06active2\xb6\x03\n" +
	"\fRegistration\x12;\n" +
	"\x06Accept\x12\x17.registration.v1.Update\x1a\x18.registration.v1.Receipt\x12A\n" +
	"\x05Claim\x12\x1d.registration.v1.ClaimRequest\x1a\x19.registration.v1.Delivery\x12A\n" +
	"\bComplete\x12\x1b.registration.v1.Completion\x1a\x18.registration.v1.Receipt\x12I\n" +
	"\x06Export\x12\x1e.registration.v1.ExportRequest\x1a\x1f.registration.v1.ExportResponse\x12L\n" +
	"\aMembers\x12\x1f.registration.v1.MembersRequest\x1a .registration.v1.MembersResponse\x12J\n" +
	"\n" +
	"SyncMember\x12\".registration.v1.SyncMemberRequest\x1a\x18.registration.v1.ReceiptB$Z\"registration.local/backend/api;apib\x06proto3"

var (
	file_api_registration_proto_rawDescOnce sync.Once
	file_api_registration_proto_rawDescData []byte
)

func file_api_registration_proto_rawDescGZIP() []byte {
	file_api_registration_proto_rawDescOnce.Do(func() {
		file_api_registration_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_registration_proto_rawDesc), len(file_api_registration_proto_rawDesc)))
	})
	return file_api_registration_proto_rawDescData
}

var file_api_registration_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_api_registration_proto_goTypes = []any{
	(*Update)(nil),            // 0: registration.v1.Update
	(*Receipt)(nil),           // 1: registration.v1.Receipt
	(*Field)(nil),             // 2: registration.v1.Field
	(*Button)(nil),            // 3: registration.v1.Button
	(*View)(nil),              // 4: registration.v1.View
	(*ClaimRequest)(nil),      // 5: registration.v1.ClaimRequest
	(*Delivery)(nil),          // 6: registration.v1.Delivery
	(*Completion)(nil),        // 7: registration.v1.Completion
	(*ExportRequest)(nil),     // 8: registration.v1.ExportRequest
	(*ExportResponse)(nil),    // 9: registration.v1.ExportResponse
	(*MembersRequest)(nil),    // 10: registration.v1.MembersRequest
	(*MembersResponse)(nil),   // 11: registration.v1.MembersResponse
	(*SyncMemberRequest)(nil), // 12: registration.v1.SyncMemberRequest
}
var file_api_registration_proto_depIdxs = []int32{
	2,  // 0: registration.v1.View.fields:type_name -> registration.v1.Field
	3,  // 1: registration.v1.View.buttons:type_name -> registration.v1.Button
	4,  // 2: registration.v1.Delivery.view:type_name -> registration.v1.View
	0,  // 3: registration.v1.Registration.Accept:input_type -> registration.v1.Update
	5,  // 4: registration.v1.Registration.Claim:input_type -> registration.v1.ClaimRequest
	7,  // 5: registration.v1.Registration.Complete:input_type -> registration.v1.Completion
	8,  // 6: registration.v1.Registration.Export:input_type -> registration.v1.ExportRequest
	10, // 7: registration.v1.Registration.Members:input_type -> registration.v1.MembersRequest
	12, // 8: registration.v1.Registration.SyncMember:input_type -> registration.v1.SyncMemberRequest
	1,  // 9: registration.v1.Registration.Accept:output_type -> registration.v1.Receipt
	6,  // 10: registration.v1.Registration.Claim:output_type -> registration.v1.Delivery
	1,  // 11: registration.v1.Registration.Complete:output_type -> registration.v1.Receipt
	9,  // 12: registration.v1.Registration.Export:output_type -> registration.v1.ExportResponse
	11, // 13: registration.v1.Registration.Members:output_type -> registration.v1.MembersResponse
	1,  // 14: registration.v1.Registration.SyncMember:output_type -> registration.v1.Receipt
	9,  // [9:15] is the sub-list for method output_type
	3,  // [3:9] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_api_registration_proto_init() }
func file_api_registration_proto_init() {
	if File_api_registration_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_registration_proto_rawDesc), len(file_api_registration_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_registration_proto_goTypes,
		DependencyIndexes: file_api_registration_proto_depIdxs,
		MessageInfos:      file_api_registration_proto_msgTypes,
	}.Build()
	File_api_registration_proto = out.File
	file_api_registration_proto_goTypes = nil
	file_api_registration_proto_depIdxs = nil
}
